import Head from "next/head";
import PostsList from "../components/posts/PostsList";
import PostForm from "../components/posts/PostForm";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
        <PostForm />
        <PostsList />
      </>
    </>
  );
}
